<?php
//CSS
require_once('C:\wamp64\www\VSApp\freshshop\css\all.css');
require_once('C:\wamp64\www\VSApp\freshshop\css\animate.css');
require_once('C:\wamp64\www\VSApp\freshshop\css\baguetteBox.min.css');
require_once('C:\wamp64\www\VSApp\freshshop\css\bootsnav.css');
require_once('C:\wamp64\www\VSApp\freshshop\css\bootstrap-select.css');
require_once('C:\wamp64\www\VSApp\freshshop\css\bootstrap.min.css');
require_once('C:\wamp64\www\VSApp\freshshop\css\carousel-ticker.css');
require_once('C:\wamp64\www\VSApp\freshshop\css\code_animate.css');
require_once('C:\wamp64\www\VSApp\freshshop\css\custom.css');
require_once('C:\wamp64\www\VSApp\freshshop\css\jquery-ui.css');
require_once('C:\wamp64\www\VSApp\freshshop\css\owl.carousel.min.css');
require_once('C:\wamp64\www\VSApp\freshshop\css\responsive.css');
require_once('C:\wamp64\www\VSApp\freshshop\css\style.css');
require_once('C:\wamp64\www\VSApp\freshshop\css\superslides.css');

//JS
require_once('C:\wamp64\www\VSApp\freshshop\js\baguetteBox.min.js');
require_once('C:\wamp64\www\VSApp\freshshop\js\bootsnav.js');
require_once('C:\wamp64\www\VSApp\freshshop\js\bootstrap-select.js');
require_once('C:\wamp64\www\VSApp\freshshop\js\bootstrap.min.js');
require_once('C:\wamp64\www\VSApp\freshshop\js\contact-form-script.js');
require_once('C:\wamp64\www\VSApp\freshshop\js\custom.js');
require_once('C:\wamp64\www\VSApp\freshshop\js\form-validator.min.js');
require_once('C:\wamp64\www\VSApp\freshshop\js\images-loded.min.js');
require_once('C:\wamp64\www\VSApp\freshshop\js\inewsticker.js');
require_once('C:\wamp64\www\VSApp\freshshop\js\isotope.min.js');
require_once('C:\wamp64\www\VSApp\freshshop\js\jquery-3.2.1.min.js');
require_once('C:\wamp64\www\VSApp\freshshop\js\jquery-ui.js');
require_once('C:\wamp64\www\VSApp\freshshop\js\jquery.nicescroll.min.js');
require_once('C:\wamp64\www\VSApp\freshshop\js\jquery.superslides.min.js');
require_once('C:\wamp64\www\VSApp\freshshop\js\owl.carousel.min.js');
require_once('C:\wamp64\www\VSApp\freshshop\js\popper.min.js');